# This file was generated by GoReleaser. DO NOT EDIT.
cask "todo" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "ff3f86055b73251f87a328d2c1961e6e1f22bc004ac9e13fd48f5d5f46198f7e"
      url "https://github.com/andresbott/todo/releases/download/v#{version}/todo_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bd8cffe966370f568302a058e443c9dd9dde50a5479000cfa69384b527d48f53"
      url "https://github.com/andresbott/todo/releases/download/v#{version}/todo_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fd3461779ccc97512f8fb4a601dffb0602c319b49a6b64d1406fa83e27e0881f"
      url "https://github.com/andresbott/todo/releases/download/v#{version}/todo_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "11ebcd9f643a662ac930d051c35bc1b963c5a7d1e8477c304c220f0de262c6ca"
      url "https://github.com/andresbott/todo/releases/download/v#{version}/todo_Linux_x86_64.tar.gz"
    end
  end

  name "todo"
  desc "Keyboard-driven terminal TODO manager backed by plain Markdown files"
  homepage "https://github.com/andresbott/todo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "todo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/todo"]
    end
  end

  # No zap stanza required
end
