# This file was generated by GoReleaser. DO NOT EDIT.
cask "todo" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "cdbe430e0578651ebc1693c3ae7345ec14d2c157925ea662ed82045df6c40203"
      url "https://github.com/andresbott/todo/releases/download/v#{version}/todo_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a76aa8518976f4210d7bad2246914b85a44624e958c731ca57915a79e1ed07d6"
      url "https://github.com/andresbott/todo/releases/download/v#{version}/todo_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cc89c7836b148a5d77e5db71324d9efcfba199b19b1359fa7094bbd8b117e09f"
      url "https://github.com/andresbott/todo/releases/download/v#{version}/todo_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5e16801231c575476e83069268972a62acdae7e3e123cec561d061ac19b790a7"
      url "https://github.com/andresbott/todo/releases/download/v#{version}/todo_Linux_arm64.tar.gz"
    end
  end

  name "todo"
  desc "Keyboard-driven terminal TODO manager backed by plain Markdown files"
  homepage "https://github.com/andresbott/todo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "todo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/todo"]
    end
  end

  # No zap stanza required

end
