# This file was generated by GoReleaser. DO NOT EDIT.
cask "todo" do
  version "0.4.3"

  on_macos do
    on_arm do
      sha256 "fab97bea109b88bd2492a6d01b6ee164577036f38d0fe0b802ebd6b8f0e66730"
      url "https://github.com/andresbott/todo/releases/download/v#{version}/todo_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "51561639e2e30d4feb42f94d036f587be11d4f369e1cc998e4a46dae32deb244"
      url "https://github.com/andresbott/todo/releases/download/v#{version}/todo_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4acd6713590de9568e546faa400cdb353bab34db302cdbdaa1f8602ed4ea2d9b"
      url "https://github.com/andresbott/todo/releases/download/v#{version}/todo_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8e4e5af2639b9218bd741ad76afd665be93ed3bb220c2fee95adbaf44b4c3a80"
      url "https://github.com/andresbott/todo/releases/download/v#{version}/todo_Linux_x86_64.tar.gz"
    end
  end

  name "todo"
  desc "Keyboard-driven terminal TODO manager backed by plain Markdown files"
  homepage "https://github.com/andresbott/todo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "todo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/todo"]
    end
  end

  # No zap stanza required
end
